### ISSUE TITLE
Emojis Don't Show Up Properly

### ISSUE THREAD

**Issue by UsefullPig** [RadBuilder/EmojiChat#8]
### What steps will reproduce the issue?  
1. Type : grinning : in Minecraft's chat or send a message through Discord SRV containing a standard emote.

### What was supposed to happen?  
Emojis were supposed to display in the chat like this "😀" when you type ": grinning :" for example.

### What happened instead?  
You get characters like this
![image](https://user-images.githubusercontent.com/39463463/68728026-5dc0ea00-0583-11ea-8e4f-b0095dc07ed8.png)
But they show up on Discord correctly.

### What Spigot version are you using?  
```
[19:34:29 INFO]: This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[19:34:29 INFO]: Checking version, please wait...
[19:34:29 INFO]: Previous version: git-Paper-209 (MC: 1.14.4)
[19:34:29 INFO]: You are running the latest version
```

### What plugins do you have installed?  
`[19:35:13 INFO]: Plugins (20): BannerBoard*, ChopTree3, CleanroomGenerator*, CMI, DiscordSRV, EasyBackup, EmojiChat, LagMonitor*, Minecord*, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, ProtocolLib, Residence, SelectionVisualizer, ServerListPlus*, UltraCustomizer, UltraPermissions, Vault*, WorldEdit`

### Are any errors related to EmojiChat in your console or logs? If so, paste below.  
```
[19:28:13 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.6.15.6
java.lang.NoSuchMethodError: github.scarsz.discordsrv.DiscordSRV.getMainTextChannel()Lgithub/scarsz/discordsrv/dependencies/jda/core/entities/TextChannel;
        at com.Zrips.CMI.Modules.DiscordSRV.DiscordSRVManager.sendDiscordMessage(DiscordSRVManager.java:45) ~[?:?]
        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventExtra(NickNameListener.java:170) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor416.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-226]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-226]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1713) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.14.4.jar:git-Paper-226]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.14.4.jar:git-Paper-226]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by UsefullPig** [comment]
I'm a fool. I remembered that you have to allow the server resource pack to install 🤦‍♂
